### ISSUE TITLE
Thanks, I like this a lot...

### ISSUE THREAD

**Issue by sarnold** [m3047/tcp_only_forwarder#2]
Especially after looking at the current crop of alternatives, testing a few (my second choice would probably be stubby).  Besides the usual dnscrypt-proxy, getdns, etc, I must've looked at a couple of dozen python implementations on github alone, and yours is by far the cleanest/most elegant one I found.  I added/updated the init/config stuff in my fork but I couldn't find a reason to touch anything else (but I'm an OS guy so I also couldn't use the repo name for the ebuild ;)

**Comment by m3047** [comment]
Thanks! I appreciate the extra set of eyes. I have no investment in the naming whatsoever. In my "infinite free time" I suppose I'd contemplate connection re-use; but it is heartbreakingly simple as-is (there is a lot of confusion surrounding UDP vs TCP in DNS).

Stubby is not bad as a COTS tool. If you're an "OS guy" then I suppose I'm a "DNS guy". Which one would I want to modify for experimental purposes? I'd choose something written in Python rather than C unless I really needed the speed.

I don't see anything actionable here, so I'll close this in a day or two. Anything you need man, just let me know!

**Comment by m3047** [comment]
Nothing to do here, so I'm closing this. Please let me know if this makes it into a distro: if there's a mailing list I should join, that sort of thing.
